FROM python:3.10-slim

WORKDIR /deployments

COPY . .

RUN apt-get update \
    && apt-get -y install libpq-dev gcc \
    && pip install psycopg2

RUN pip install -r requirements/prefect.txt
RUN pip install -r requirements/prod.txt

CMD ["sh", "-c", "sleep 30 && python prefect/deployment.py"]
