name: prefect
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  prefect:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - env:
          PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements/prefect.txt
          pip install -r requirements/prod.txt
          prefect config set PREFECT_API_URL=$PREFECT_API_URL
          python -m src.deploy_prefect.deployment
