name: prefect

on:
  pull_request:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - env:
          PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements/prefect.txt
          pip install -r requirements/prod.txt
          prefect config set PREFECT_API_URL=$PREFECT_API_URL
          python -m src.deploy_prefect.deployment
